GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
  "title": "Rich dad poor dad"
}

###

PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Rich Dad Poor Dad"
}

###

DELETE http://localhost:3001/books/2 HTTP/1.1
Content-Type: application/json